import pygame

# color values
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
RED = (255, 0, 0)
GREEN = (0, 255, 0)
DARK_BLUE = (0, 0, 204)
LIGHT_BLUE = (0, 255, 255)
YELLOW = (255, 255, 0)
ORANGE = (255, 128, 0)
PURPLE = (153, 51, 255)

BG_COLOR = BLACK
TEXT_COLOR = WHITE

# useful constants
BLOCK_SIZE = 20
LINE_SIZE = 1
SPACE_SIZE = BLOCK_SIZE + LINE_SIZE
TEXT_SIZE = 16

# holder constants
HOLDER_GRID_DIMENSIONS = (6, 6)
HOLDER_BOX_DIMENSIONS = (
    HOLDER_GRID_DIMENSIONS[0] * BLOCK_SIZE
    + (HOLDER_GRID_DIMENSIONS[0] - 1) * LINE_SIZE,
    HOLDER_GRID_DIMENSIONS[1] * BLOCK_SIZE
    + (HOLDER_GRID_DIMENSIONS[1] - 1) * LINE_SIZE,
)
HOLDER_LABEL_DIMENSIONS = (HOLDER_BOX_DIMENSIONS[0], 50)
HOLDER_DIMENSIONS = (
    HOLDER_BOX_DIMENSIONS[0],
    HOLDER_BOX_DIMENSIONS[1] + HOLDER_LABEL_DIMENSIONS[1],
)
HOLDER_SCREEN_POS = (0, 0)

# score constants
SCORE_DIMENSIONS = (HOLDER_DIMENSIONS[0], 100)  # 100 wide, 100 tall
SCORE_SCREEN_POS = (0, HOLDER_DIMENSIONS[1])

SOFT_DROP_SCORE = 1
HARD_DROP_SCORE = 2
LINE_CLEAR_SCORES = {0: 0, 1: 100, 2: 300, 3: 500, 4: 800}
MAX_INSTANT_SCORE = 840
LINE_CLEAR_WEIGHT = 4
SCORE_DIVISION = {"line_clear": 1, "ending_height": 0.3, "line_add": 1}


# main player constants
PLAYER_GRID_DIMENSIONS = (10, 20)
PLAYER_DIMENSIONS = (
    PLAYER_GRID_DIMENSIONS[0] * BLOCK_SIZE
    + (PLAYER_GRID_DIMENSIONS[0] - 1) * LINE_SIZE,
    PLAYER_GRID_DIMENSIONS[1] * BLOCK_SIZE
    + (PLAYER_GRID_DIMENSIONS[1] - 1) * LINE_SIZE,
)
PLAYER_SCREEN_POS = (SCORE_DIMENSIONS[0], 0)
BLOCK_START = (3 * SPACE_SIZE, 0)

KEY_MAPPINGS = {
    pygame.K_UP: "spin right",
    pygame.K_DOWN: "soft drop",
    pygame.K_LEFT: "left",
    pygame.K_RIGHT: "right",
    pygame.K_z: "spin left",
    pygame.K_c: "hold",
    pygame.K_SPACE: "hard drop",
    pygame.K_q: "nothing",
}


# next pieces constants
NEXT_PIECES_GRID_DIMENSIONS = (6, 12)
NEXT_PIECES_BOX_DIMENSIONS = (
    NEXT_PIECES_GRID_DIMENSIONS[0] * BLOCK_SIZE
    + (NEXT_PIECES_GRID_DIMENSIONS[0] - 1) * LINE_SIZE,
    NEXT_PIECES_GRID_DIMENSIONS[1] * BLOCK_SIZE
    + (NEXT_PIECES_GRID_DIMENSIONS[1] - 1) * LINE_SIZE,
)
NEXT_PIECES_LABEL_DIMENSIONS = (NEXT_PIECES_BOX_DIMENSIONS[0], 50)
NEXT_PIECES_DIMENSIONS = (
    NEXT_PIECES_BOX_DIMENSIONS[0],
    NEXT_PIECES_LABEL_DIMENSIONS[1] + NEXT_PIECES_BOX_DIMENSIONS[1],
)
NEXT_PIECES_SCREEN_POS = (SCORE_DIMENSIONS[0] + PLAYER_DIMENSIONS[0], 0)

# all-purpose constant
FULL_WINDOW_SIZE = (
    PLAYER_DIMENSIONS[0] + SCORE_DIMENSIONS[0] + NEXT_PIECES_DIMENSIONS[0],
    max(PLAYER_DIMENSIONS[1], SCORE_DIMENSIONS[1], NEXT_PIECES_DIMENSIONS[1]),
)
TIME_BETWEEN_DOWNS = 1  # this is in seconds
STEPS_BETWEEN_DOWNS = 6
